// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGfXQnE6SmMpZtTdCiihohl2kvRxnshn0',
    appId: '1:173122852515:web:cd960b6b49acf9047d1116',
    messagingSenderId: '173122852515',
    projectId: 'appubicacionsenati',
    authDomain: 'appubicacionsenati.firebaseapp.com',
    storageBucket: 'appubicacionsenati.firebasestorage.app',
    measurementId: 'G-E561D953H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDZcLPTCx1DuTM_fBG6HX8gfJTH__Ny-M',
    appId: '1:173122852515:android:c8c26a2bd40447387d1116',
    messagingSenderId: '173122852515',
    projectId: 'appubicacionsenati',
    storageBucket: 'appubicacionsenati.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwKWbd59T2JDe8Ddr_1TkXHeiaBupuRs',
    appId: '1:173122852515:ios:6da703370613e7a17d1116',
    messagingSenderId: '173122852515',
    projectId: 'appubicacionsenati',
    storageBucket: 'appubicacionsenati.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJwKWbd59T2JDe8Ddr_1TkXHeiaBupuRs',
    appId: '1:173122852515:ios:6da703370613e7a17d1116',
    messagingSenderId: '173122852515',
    projectId: 'appubicacionsenati',
    storageBucket: 'appubicacionsenati.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGfXQnE6SmMpZtTdCiihohl2kvRxnshn0',
    appId: '1:173122852515:web:4bc12d436b83626d7d1116',
    messagingSenderId: '173122852515',
    projectId: 'appubicacionsenati',
    authDomain: 'appubicacionsenati.firebaseapp.com',
    storageBucket: 'appubicacionsenati.firebasestorage.app',
    measurementId: 'G-265RBK543E',
  );
}
